# -*- coding: utf-8 -*-
"""CIFAR_10-KNN Classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e0E_o-Qps4W7KWfuxIAwWtX7k-wrruyg

Import necessary libraries:
"""

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score
from tensorflow.keras import datasets

"""Load and preprocess the CIFAR-10 dataset:

"""

(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()

# Flatten the images and convert labels to 1D arrays
x_train = x_train.reshape(x_train.shape[0], -1)
x_test = x_test.reshape(x_test.shape[0], -1)
y_train = y_train.ravel()
y_test = y_test.ravel()

# Normalize pixel values to be between 0 and 1
x_train, x_test = x_train / 255.0, x_test / 255.0

"""Train a K-Nearest Neighbor classifier:"""

# Choose the number of neighbors (k)
k = 5

knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(x_train, y_train)

"""Evaluate the classifier:"""

y_pred = knn.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Classification report
print(classification_report(y_test, y_pred))